eobicho/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings

app_name = 'eobicho'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('pet.urls')),

]

pet/urls.py
from django.urls import path
#from .views import form, listPet
from . import views

app_name = 'pet'

urlpatterns = [
    path('', views.paginacao, name='list'),
    path('newpet', views.form, name='form'),
    path('update/<int:pk>/', views.updatePet.as_view(), name='update'),
    path('detail/<int:pk>/', views.detailPet, name='detail'),
    path('delete/<int:pk>/', views.deletePet.as_view(), name='delete'),
    path('formInspecaoPet/', views.FormInspecaoPet, name='InspecaoPet'),
        
] 

accounts/models.py
from django.db import models

# Create your models here.

pet/models.py
from django.db import models

ESPECIE_CHOICES = (
	('cachorro', 'Cachorro'),
	('gato', 'Gato'),
	('coelho', 'Coelho'),
	('cavalo', 'Cavalo'),
	('peixe', 'Peixe')
)

RACA_CACHORRO = (

	('Afegão Hound','Afegão Hound'),
	('Affenpinscher','Affenpinscher'),
	('Airedale Terrier','Airedale Terrier'),
	('Akita', 'Akita'),
	('American Staffordshire Terrier','American Staffordshire Terrier'),
	('Basenji','Basenji'),
	('Basset Hound','Basset Hound'),
	('Beagle','Beagle'),
	('Beagle Harrier','Beagle Harrier'),
	('Bearded Collie','Bearded Collie'),
	('Bedlington Terrier','Bedlington Terrier'),
	('Bichon Frisé','Bichon Frisé'),
	('Bloodhound','Bloodhound'),
	('Bobtail','Bobtail'),
	('Boiadeiro Australiano','Boiadeiro Australiano'),
	('Boiadeiro Bernês','Boiadeiro Bernês'),
	('Border Collie','Border Collie'),
	('Border Terrier','Border Terrier'),
	('Borzoi','Borzoi'),
	('Boston','Boston Terrier'),
	('Boxer','Boxer'),
	('Buldogue Francês','Buldogue Francês'),
	('Buldogue Inglês','Buldogue Inglês'),
	('Bul Terrier','Bull Terrier'),
	('Bulmastife','Bulmastife'),
	('Cairn Terrier','Cairn Terrier'),
	('Cane Corso','Cane Corso'),
	('Cão de Água Português','Cão de Água Português'),
	('Cão de Crista Chinês','Cão de Crista Chinês'),
	('Cavalier King Charles Spaniel','Cavalier King Charles Spaniel'),
	('Chesapeake Bay Retriever','Chesapeake Bay Retriever'),
	('Chihuahua','Chihuahua'),
	('Chow Chow','Chow Chow'),
	('Cocker Spaniel Americano','Cocker Spaniel Americano'),
	('Cocker Spaniel Inglês','Cocker Spaniel Inglês'),
	('Collie','Collie'),
	('Coton de Tuléar','Coton de Tuléar'),
	('Dachshund','Dachshund'),
	('Dálmata','Dálmata'),
	('Dandie Dinmont Terrier','Dandie Dinmont Terrier'),
	('Dobermann','Dobermann'),
	('Dogo Argentino','Dogo Argentino'),
	('Dogue Alemão','Dogue Alemão'),
	('Fila Brasileiro','Fila Brasileiro'),
	('Fox Terrier','Fox Terrier (Pelo Duro e Pelo Liso)'),
	('Foxhound Inglês','Foxhound Inglês'),
	('Galgo Escocês','Galgo Escocês'),
	('Galgo Irlandês','Galgo Irlandês'),
	('Golden Retriever','Golden Retriever'),
	('Grande Boiadeiro Suiço','Grande Boiadeiro Suiço'),
	('Greyhound','Greyhound'),
	('Grifo da Bélgica','Grifo da Bélgica'),
	('Husky Siberiano','Husky Siberiano'),
	('Jack Russell Terrier','Jack Russell Terrier'),
	('King Charles','King Charles'),
	('Komondor','Komondor'),
	('Labradoodle','Labradoodle'),
	('Labrador Retriever','Labrador Retriever'),
	('Lakeland Terrier','Lakeland Terrier'),
	('Leonberger','Leonberger'),
	('Lhasa Apso','Lhasa Apso'),
	('Lulu da Pomerânia','Lulu da Pomerânia'),
	('malamute do Alasca','Malamute do Alasca'),
	('Maltês','Maltês'),
	('Mastife','Mastife'),
	('Mastim Napolitano','Mastim Napolitano'),
	('Mastim Tibetano','Mastim Tibetano'),
	('Norfolk Terrier','Norfolk Terrier'),
	('Norwich Terrier','Norwich Terrier'),
	('Papillon','Papillon'),
	('Pastor Alemão','Pastor Alemão'),
	('Pastor Australiano','Pastor Australiano'),
	('Pastor Suiço', 'Pastor Suiço'),
	('Pinscher Miniatura','Pinscher Miniatura'),
	('Poodle','Poodle'),
	('Pug','Pug'),
	('Rottweiler','Rottweiler'),
	('ShihTzu','ShihTzu'),
	('Silky Terrier','Silky Terrier'),
	('Skye Terrier','Skye Terrier'),
	('Staffordshire Bull Terrier','Staffordshire Bull Terrier'),
	('Terra Nova','Terra Nova'),
	('Terier Escocês','Terrier Escocês'),
	('Tosa','Tosa'),
	('Welsh Corgi (Cardigan)','Welsh Corgi (Cardigan)'),
	('Welsh Corgi (Pembroke)','Welsh Corgi (Pembroke)'),
	('West Highland White Terrier','West Highland White Terrier'),
	('Whippet','Whippet'),
	('Xoloitzcuintli','Xoloitzcuintli'),
	('Yorkshire Terrier','Yorkshire Terrier'),
	('Sem Raça Definida (SRD)','Sem Raça Definida (SRD)'),
	
)

TEMPERAMENTO_CHOICES =(
	('Agressivo','Agressivo'),
    ('Manso','Manso'),
    ('Anti-social','Anti-social'),
    ('Social','Social'),
    ('Agitado','Agitado'),
    ('Calmo','Calmo'),
    ('Introvertido','Introvertido'),
    ('Extrovertido','Extrovertido'),
    ('Obediente','Obediente'),
    ('Independente','Independente'),
    ('Curioso','Curioso'),
    ('Independente','Indiferente'),
    ('Ousado','Ousado'),
    ('Tímido','Tímido'),
)
PELAGEM_CHOICES = (
	('Levemente Aspera','Levemente Aspera'),
	('Fios Lisos e Longos', 'Fios Lisos e Longos')
)
COLORACAO_CHOICES = (
	('amarelo', 'Amarelo'),
	('branco', 'Branco'),
	('caramelo', 'Caramelo'),
	('marrom', 'Marrom'),
	('preto','Preto')
)

class formPet(models.Model):
	nome = models.CharField('Nome',max_length=150)
	apelido = models.CharField('Apelido',max_length=30)
	aniversario = models.DateField('Aniversário', blank=True, null=True)
	idade = models.IntegerField('Idade')
	peso = models.IntegerField('Peso(kg)')
	tamanho = models.IntegerField('Tamanho')
	especie = models.CharField('Especie',max_length=10, choices=ESPECIE_CHOICES)
	racaCachorro = models.CharField('Raça do Cachorro',max_length=150, choices=RACA_CACHORRO)
	temperamento = models.CharField('Temperamento',max_length=60, choices=TEMPERAMENTO_CHOICES)
	pelagem = models.CharField('Pelagem',max_length=150, choices=PELAGEM_CHOICES)
	coloracao = models.CharField('Coloração',max_length=60, choices=COLORACAO_CHOICES)
	tamanho = models.IntegerField('Tamanho(cm)',)
	caracteristicas = models.CharField('Caracteristicas', max_length=200)
	def __str__(self):
		return self.nome	

	

pet/forms.py
from django import forms
from datetime import datetime
from .models import formPet

class CadastroPet(forms.ModelForm):
	aniversario = forms.DateField(
        label = (u'Aniversário'),
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'maxlength':'10',}), 
        input_formats=['%d/%m/%Y',]
    )
	class Meta:
		model = formPet
		fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

pet/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import UpdateView
from django.views.generic.edit import DeleteView
from .models import formPet
from .forms import CadastroPet

def FormInspecaoPet(request):
	return render(request, 'formInspecao.html')

#Cadastro 
def form(request):
    if request.method == 'GET':
        form = CadastroPet()
        context = {
            'form':form
        }
        return render(request, 'pet/formpet_form.html', context=context)
    else:
        form = CadastroPet(request.POST)
        if form.is_valid():
            pet = form.save()
            form = CadastroPet()
        
        context = {
            'form':form
        }
        
        return render(request, 'pet/formpet_form.html', context=context)

#Lista de Exibição e Pesquisa
def paginacao(request):
    parametro_page = request.GET.get('page', '1')
    parametro_limit = request.GET.get('limit', '5')
    
    if not (parametro_limit.isdigit() and int(parametro_limit)>0):
        parametro_limit = '10'

    pets = formPet.objects.all()
    pets_paginator = Paginator(pets, parametro_limit)

    search = request.GET.get('search')
    if search:
        pets = pets.filter(nome__icontains=search)

    try:
        page = pets_paginator.page(parametro_page)
    except (EmptyPage, PageNotAnInteger):
        page = pets_paginator.page(1)
       

    context = {
        'items_list': ['5','10', '20', '30', '50'],
        'qnt_page':parametro_limit,
        'pets': page,
        'object_list':pets
    }
    return render(request, 'test.html', context)



#Atualização
def detailPet(request, pk):
    template ='pet/formpet_detail.html'
    obj = formPet.objects.get(pk=pk)
    context = { 'object': obj }
    return render(request, template, context) 


#Atualização
class updatePet(UpdateView):
    template_name = 'pet/formpet_update.html'
    model = formPet
    fields = '__all__'
    success_url = reverse_lazy('pet:list')

#Apagar    
class deletePet(DeleteView):
    queryset = formPet.objects.all()
    success_url = reverse_lazy('pet:list')
    

pet/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="É o Bicho - Agropecuária" />
    <title>É O BICHO</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- JavaScript -->
    <script type="text/javascript" href="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" href="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
    <header id="wrap-header">
      <div class="container">
        <a href="{% url 'pet:form' %}"><img class="card-img-top" alt="logo" src="{% static 'img/logo.png'%}"></a>
      </div>  
        <!-- Nav Menu -->
          <nav class="navbar navbar-expand-lg navbar-light wrap-nav">
            <div class="container">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                  <li class="nav-item">
                    <a class="nav-link"href="{% url 'pet:list' %}">Animais</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pet:form' %}">Cadastrar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pet:InspecaoPet' %}">Inspeção Física</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav><!-- /NAV -->
         
    </header><!-- /HEADER -->
    <main id="wrap-main">
      
      {% block content %} 
      {% endblock content %}


    </main><!-- /MAIN -->
    <footer id="wrap-footer">
        
    </footer><!-- /FOOTER -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

pet/templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}
{% block content %}
{% if user.is_authenticated %}
<form class="container" method="POST" action=".">
	{% csrf_token %}
  <br>
  <h2 class="">IDENTIFICAÇÃO DO PET</h2>
  <div class="form-row">
    <div class="col col-lg-5 mb-3">
      	{{ form.nome|as_crispy_field }}
    </div>
    <div class="col-md-4 mb-3">
      {{ form.apelido|as_crispy_field }}
    </div>
    <div class="col-md-3 mb-3">
      {{ form.aniversario|as_crispy_field }}
    </div>
  
    <div class="col-md-3 mb-3">
      {{ form.idade|as_crispy_field }}
    </div>

    <div class="col-md-3 mb-3">
      {{ form.peso|as_crispy_field }}
    </div>

    <div class="col-md-3 mb-3">
      {{ form.especie|as_crispy_field }}
    </div>
      
    <div class="col-md-3 mb-3">
      {{ form.racaCachorro|as_crispy_field }}
    </div>

    <div class="col-md-3 mb-3">
     {{ form.temperamento|as_crispy_field }}
    </div>
 
    <div class="col-md-3 mb-3">
      {{ form.pelagem|as_crispy_field }}
    </div>
  
    <div class="col-md-3 mb-3">
      {{ form.coloracao|as_crispy_field }}
    </div>
    
    <div class="col-md-3 mb-3">
      {{ form.tamanho|as_crispy_field }}  
    </div>
    
    <div class="col-md-3 mb-3">
      {{ form.caracteristicas|as_crispy_field }}  
    </div>
  </div>
 	
   <button class="btn btn-primary btn-lg" type="submit">Cadastrar</button>
</form><!-- /FORM IDENTIFICAÇÃO DOS PETS -->
<br>
{% endif %}
{% endblock content %}

pet/templates/formInspecao.html
{% extends 'site/base.html' %}
{% block title %}
{{block.super}} - Inspeção do Pet
{% endblock title %}
{% block content %}
<!-- FORM INSPEÇÃO FÍSICA E ESTETÍCA -->
<form class="container">
  <h3>Inspeção Física/Estetíca</h3>
  <div class="form-row">
    <div class="col-lg-6 mb-3">
      <h4>Inspeção do Pelo:</h4>
      <textarea class="form-control"></textarea>
    </div>

    <div class="col-lg-6 mb-3">
      <h4>Inspeção das Unhas:</h4>
      <textarea class="form-control"></textarea>
    </div>

    <div class="col-lg-6 mb-3">
      <h4>Inspeção dos olhos:</h4>
      <textarea class="form-control"></textarea>
    </div>

    <div class="col-lg-6 mb-3">
      <h4>Inspeção Bucal:</h4>
      <textarea class="form-control"></textarea>
    </div>

    <div class="col-lg-6 mb-3">
      <h4>Inspeção da Pele:</h4>
      <textarea class="form-control"></textarea>
    </div>

    <div class="col-lg-6 mb-3">
      <h4>Inspeção das patas:</h4>
      <textarea class="form-control"></textarea>
    </div>
    
    <div class="col-lg-6 mb-3">
      <h4 class="">Inspeção auricular:</h4>
      <div class="form-row">
        <div class="col col-sm-6">
          <input type="checkbox" class="checkbox" name="inflamação" placeholder="inflamação"><label>Inflamação<label>
        </div>
        <div class="col col-sm-6">
          <input type="checkbox" class="checkbox" name="infecção" placeholder="infecção"><label>Infecção</label>
        </div>
      </div>  
      <label>Observações:</label>
      <textarea class="form-control"></textarea>
    </div><!-- /Auricular -->
  
  </div>

 
  <button class="btn btn-primary btn-lg" type="submit">Enviar</button>
</form>
{% endblock content %}

pet/templates/pet/formpet_confirm_delete.html
{% extends 'site/base.html' %}
{% block title%}
{{block.super}} - Apagar Pet
{% endblock title %}
{% block content %}
<p>Tem certeza que deseja apagar o registro do '{{ object.nome }}'?</p>
	<form method="POST">
		{% csrf_token %}
		<button class="btn btn-primary btn-md" type="submit">Sim, tenho certeza!</button>
		<button class="btn btn-primary btn-md" type="reset" onclick="location.href='{% url 'pet:list' %}'">Não, desejo voltar!</button>
	</form>
</body>
{% endblock %}

pet/templates/pet/formpet_detail-bkp.html
{% extends 'base.html' %}
{% block content %}
<section class="container">
	<h1>Ficha Técnica do Pet</h1>
	<form class="form-row">
		<div>
			<div>
				<label class="font-weight-bold">Nome: </label>
				<label class="text-monospace">{{object.nome}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Apelido: </label>
				<label class="text-monospace">{{object.apelido}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Aniversário: </label>
				<label class="text-monospace">{{object.aniversario}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Idade: </label>
				<label class="text-monospace">{{object.idade}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Peso(kg): </label>
				<label class="text-monospace">{{object.peso}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Tamanho: </label>
				<label class="text-monospace">{{object.tamanho}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Especie: </label>
				<label class="text-monospace">{{object.especie}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Raça: </label>
				<label class="text-monospace">{{object.racaCachorro}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Temperamento: </label>
				<label class="text-monospace">{{object.temperamento}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Pelagem: </label>
				<label class="text-monospace">{{object.pelagem}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Coloração: </label>
				<label class="text-monospace">{{object.coloracao}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Tamanho(cm): </label>
				<label class="text-monospace">{{object.tamanho}}</label> 
			</div>
			<div>
				<label class="font-weight-bold">Caracteristicas: </label>
				<label class="text-monospace">{{object.caracteristicas}}</label>
			</div>
			
		</div>		
	</form>
	<button class="btn btn-primary btn-lg" type="submit" onclick="location.href='{% url 'pet:list'%}'">Voltar</button>
</section>

{% endblock %}

pet/templates/pet/formpet_detail.html
{% extends 'site/base.html' %}
{% block title%}
{{block.super}} - Ficha técnica
{% endblock title %}
{% block content %}
<section class="container">
	<h1>Ficha Técnica do Pet</h1>


<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="../../static/img/curto.jpg" alt="Imagem de capa do card">
  <div class="card-body">
    <h5 class="card-title"><label class="text-monospace">{{object.nome}}</label></h5>
    <div class="card-text">
    	<div>
			<label class="font-weight-bold">Apelido: </label>
			<label class="text-monospace">{{object.apelido}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Aniversário: </label>
			<label class="text-monospace">{{object.aniversario}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Idade: </label>
			<label class="text-monospace">{{object.idade}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Peso(kg): </label>
			<label class="text-monospace">{{object.peso}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Tamanho(cm): </label>
			<label class="text-monospace">{{object.tamanho}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Especie: </label>
			<label class="text-monospace">{{object.especie}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Raça: </label>
			<label class="text-monospace">{{object.racaCachorro}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Temperamento: </label>
			<label class="text-monospace">{{object.temperamento}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Pelagem: </label>
			<label class="text-monospace">{{object.pelagem}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Coloração: </label>
			<label class="text-monospace">{{object.coloracao}}</label> 
		</div>
		<div>
			<label class="font-weight-bold">Caracteristicas: </label>
			<label class="text-monospace">{{object.caracteristicas}}</label>
		</div>
    </div>
    <button class="btn btn-primary btn-lg" type="submit" onclick="location.href='{% url 'pet:list'%}'">Voltar</button>
  </div>
</div>
	
	
</section>

{% endblock %}

pet/templates/pet/formpet_list.html
{% extends 'site/base.html' %}
{% block title%}
{{block.super}} - Home
{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<section class="container">
	<div class="row">
		<div class="col">
			<h3 class="font-weight-bold">Lista de cadastrados</h3>
		</div>
		<div class="row justify-content-end ">
			<a class="btn btn-primary btn-lg" href="{% url 'pet:form' %}">Cadastrar Pet</a>
		</div>	
	</div>
	<!-- LISTA DE ANIMAIS CADASTRADOS -->	 
	{% csrf_token %}
	<table id="wrap-list-pet" class="table">
	  <thead class="thead-light">
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Tutor</th>
	      <th scope="col">Nome do Pet</th>
	      <th scope="col">Espécie</th>
	      <th scope="col"></th>
	    </tr>
	  </thead>
	  <tbody>
	  	 {% for pet in pets %}
		    <tr>
		   	  <th scope="row">{{pet.id}}</th>
		      <td></td>
		      <td><a href="{% url 'pet:detail' pk=pet.id %}">{{pet.nome}}</a> ({{pet.apelido}})</td>
		      <td class="text-uppercase">{{pet.especie}}</td>
		      <td class="row justify-content-end">
		      	<a class="btn btn-primary btn-md mr-sm-2" href="{% url 'pet:detail' pk=pet.id %}">Visualizar</a>
		      	<a class="btn btn-primary btn-md mr-sm-2" href="{% url 'pet:update' pk=pet.id %}">Editar</a>	
		      	<a class="btn btn-primary btn-md mr-sm-2" href="{% url 'pet:delete' pk=pet.id %}">Deletar</a>
		      </td>
		    </tr>
	    {% endfor %}
	  </tbody>
	</table>
	<!-- PAGINATOR -->
	<div class="row">
		<!-- Paginator -->
		<div class="col">
			<p class="">Itens por página:</p>
			<nav>
				<ul class="pagination pagination-sm">
				{% for qnt in items_list %}
					{% if qnt == qnt_page %}
						<li class="page-item active">
							<a class="page-link" href="#" tabindex="-1">{{ qnt }}</a>
						</li>	
						
					{% else %}
						<li class="page-item">
							<a class="page-link" href="{% url 'pet:list'%}?limit={{qnt}}">{{ qnt }}</a>
						</li>	
						
					{% endif %}
				{% endfor %}
				</ul class="pagination pagination-sm">
			</nav>
		</div><!-- /Itens por página -->
		<div class="row justify-content-end align-items-end">
			
			<nav  class="col" >
			  <ul class="pagination">
			  	{% if pets.has_previous %}
				  	<li class="page-item">
				      <a class="page-link" href="{% url 'pet:list'%}?limit={{qnt_page}}&page={{pets.previous_page_number}}">Anterior</a>
				    </li>
			    {% else %}
				    <li class="page-item disabled">
				      <a class="page-link"  href="#">Anterior</a>
				    </li>
			    {% endif %}
			    
			    {% for num in pets.paginator.page_range %}
			    	{% if num == pets.number %}
				    	<li class="page-item disabled">
				    		<a class="page-link" href="#">{{ num }}</a>
				    	</li>
			    	{% else %}
				    	<li class="page-item">
				    		<a class="page-link" href="{% url 'pet:list'%}?limit={{qnt_page}}&page={{num}}">{{ num }}</a>
				    	</li>
			    	{% endif %}	
			    {% endfor %}

				{% if pets.has_next %}	    
				    <li class="page-item">
				      <a class="page-link" href="{% url 'pet:list'%}?limit={{qnt_page}}&page={{pets.next_page_number}}">Next</a>
				    </li>
				{% else %}
					<li class="page-item disabled">
				      <a class="page-link" href="#">Next</a>
				    </li>    
				{% endif %}
			  </ul>
			</nav>
		</div>
		<!-- /Paginator -->
	</div>
</section>
{% endblock %}

pet/templates/site/navbar.html
<!-- Nav Menu -->
        <div class="sticky-top">
          <nav class="navbar sticky-top navbar-expand-lg navbar-light wrap-nav">
            <div class="container">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                  <li class="nav-item">
                    <a class="nav-link"href="{% url 'pet:list' %}">Animais</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pet:form' %}">Cadastrar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pet:InspecaoPet' %}">Inspeção Física</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav><!-- /NAV -->
        </div> 

pet/templates/test.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Teste</title>
</head>
<body>
	{% for qnt in object_list %}
		<p>{{ qnt.nome }}</p>
	{% endfor %}
</body>
</html>